server:
  port: 10102
spring:
  application:
    name: ktc-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xiesongshen/ktc.git
  rabbitmq:
    host: 192.168.60.131
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh